### ISSUE TITLE
 Latency is high

### ISSUE THREAD

**Issue by wangrunze2023** [blueconic/browscap-java#61] opened 2024-02-02 15:06 UTC
browscap-java is very slow to obtain browser information and has high latency

**Comment by paulrutter** [comment] 2024-02-03 06:37
Are you reusing the parser instsnce? You should, as otherwise it will load all rules on every instance created.

**Comment by paulrutter** [comment] 2024-02-27 06:59
Duplicate of https://github.com/blueconic/browscap-java/issues/64

**Closed by paulrutter** 2024-02-27 06:59 UTC
